spring:
  cloud:
    function:
      definition: initTeams
    stream:
      bindings:
        initTeams-in-0:
          destination: init-teams
          group: team-service
        initSeasonMapTeams-out-0:
          destination: init-season-map-teams