spring:
  cloud:
    function:
      definition: >
        fetchSeasonsForInitFixtures;
        fetchSeasonsForInitTeams;
        updateSeasonsForInitFixtures;
        initSeasonMapTeams
    stream:
      default:
        contentType: application/json
      bindings:
        fetchSeasonsForInitFixtures-in-0:
          destination: fetch-seasons-for-init-fixtures
          group: init-fixtures
        fetchTeamsForInitFixtures-out-0:
          destination: fetch-teams-for-init-fixtures
          group: init-fixtures
        updateSeasonsForInitFixtures-in-0:
          destination: update-seasons-for-init-fixtures
          group: init-fixtures
        persistTeamsForInitTeams-out-0:
          destination: persist-teams-for-init-teams

        fetchSeasonsForInitTeams-in-0:
          destination: fetch-seasons-for-init-teams
          group: init-teams
        persistSeasonMapTeamsForInitTeams-in-0:
          destination: persist-season-map-teams-for-init-teams
          group: init-teams
