server:
  port: 8082

logging:
  pattern:
    console: "%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n"
  level:
    org.springframework.amqp: DEBUG
    com.kickoff: DEBUG

spring:
  application:
    name: team-service

  jpa:
    open-in-view: false
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:postgresql://localhost:5432/team_service?stringtype=unspecified
    driver-class-name: org.postgresql.Driver
    username: root
    password: root

  rabbitmq:
    host: localhost
    port: 5672
    username: guestuser
    password: guestuser

  data:
    redis:
      host: localhost
      port: 6379

value:
  rapid:
    api:
      key: ${RapidApiKey}
  jwt:
    secret: testtesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttest
  allow-ip: ${KICKOFF_ALLOW_IP}