spring:
  cloud:
    function:
      definition: >
        fetchTeamsForInitFixtures;
        persistTeamsForInitTeams
    stream:
      default:
        contentType: application/json
      bindings:
        fetchTeamsForInitFixtures-in-0:
          destination: fetch-teams-for-init-fixtures
          group: init-fixtures
        persistFixturesForInitFixtures-out-0:
          destination: persist-fixtures-for-init-fixtures
          group: init-fixtures
        persistTeamsForInitTeams-in-0:
          destination: persist-teams-for-init-teams
          group: init-teams
        persistSeasonMapTeamsForInitTeams-out-0:
          destination: persist-season-map-teams-for-init-teams
          group: init-teams
        fetchSeasonsForInitTeams-out-0:
          destination: fetch-seasons-for-init-teams
          group: init-teams

